version: '3.7'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: magento2
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017